---
title: "*Colias* Isolation by Distance Analysis"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(geosphere)   
```

## Create Data Frame
```{r}
library(readr)
sites<-read.csv("Data/sites-all1.csv")


#Haversine Distance measure in meters
pair_dist <- distm(sites[, c("x", "y")], fun = distHaversine)
rownames(pair_dist) <- sites$site
colnames(pair_dist) <- sites$site

pair_dist <- as.data.frame.table(pair_dist)

# Rename columns
colnames(pair_dist) <- c("site1", "site2", "distance")

# Remove rows where site1 equals site2
pair_dist <- pair_dist[pair_dist$site1 != pair_dist$site2, ]
pair_dist$distance <- pair_dist$distance / 1000

pair_dist$site_pair <- paste(pair_dist$site1, pair_dist$site2, sep = "_")

```

## Upload paired Fst
```{r}
pair_fst <- read_delim("Data/weighted_fst_results.txt", delim = " ")
#pair_fst$weighted_fst <- pair_fst$Weighted_Fst

pair_fst$site_pair <- substr(pair_fst$File, 5, 9)
```

## Creating the final data file
```{r}
pair_fst_dist1 <- merge(pair_fst, pair_dist, by="site_pair", all=F)

# run the following in order ###
sites <- read.csv("Data/sites-all1.csv")
sites$site1 <- sites$site
pair_fst_dist2 <- merge(pair_fst_dist1, sites, by="site1", all=F)

sites <- read.csv("Data/sites-all1.csv")
sites$site2 <- sites$site

pair_fst_dist <- merge(pair_fst_dist2, sites, by="site2", all=F) 
###

# high-low variable

pair_fst_dist$elev_gradient <- ifelse(pair_fst_dist$elevation.x == "high" & pair_fst_dist$elevation.y == "low", 2, 
                                       ifelse(pair_fst_dist$elevation.x == "low" & pair_fst_dist$elevation.y == "high", 2,
                                              ifelse(pair_fst_dist$elevation.x == "low" & pair_fst_dist$elevation.y == "low", 1, 3)))

# east-west variable

pair_fst_dist$ew_gradient <- ifelse(pair_fst_dist$divide.x == "east" & pair_fst_dist$divide.y == "west", "east-west", 
                                    ifelse(pair_fst_dist$divide.x == "west" & pair_fst_dist$divide.y == "east", "east-west",
                                           ifelse(pair_fst_dist$divide.x == "east" & pair_fst_dist$divide.y == "east", "east-east", "west-west")))

#pair_unique$ew_gradient <- as.factor(pair_unique$ew_gradient)

## slatkin's D
  
pair_fst_dist$slatkin_D <- (pair_fst_dist$Weighted_Fst / (1-pair_fst_dist$Weighted_Fst))

#write.csv(pair_fst_dist, "Data/IBD-pair_fst_dist.csv")

pair_fst_dist <- read.csv("Data/IBD-pair_fst_dist.csv")

# Remove duplicates based on sorted pairs
# pair_fst_dist$sorted_pairs <- apply(pair_fst_dist[, c("site1", "site2")], 1, function(x) paste(sort(x), collapse = "_"))

#pair_unique <- pair_fst_dist[!duplicated(pair_fst_dist$sorted_pairs), ]

```

## Isolation by distance
```{r}
library(ggplot2)

theme_font1 <- function(base_family="Arial") {
  theme(axis.text.x=element_text(size=12),
        axis.text.y=element_text(size=12), 
        axis.title.x=element_text(size=16),
        axis.title.y=element_text(size=16),
        legend.text=element_text(size=12),
        legend.title=element_text(size=14))}


#### IDB - all ####
IDB1 <- ggplot(data=pair_fst_dist, aes(x=distance, y=slatkin_D))+
  geom_smooth(method="lm", linetype="dotted", linewidth=.8, alpha=.1, color="black", se=FALSE)+
  geom_point(size=3, shape=21, fill="lightgray")+
  xlab("Distance (km)") +
  ylab("Slatkin's D") +
  theme_classic()+
  theme_font1()

IDB1

ggsave("Ch3-IBD-update.svg", width=6, height=4)


## simple model
IBD.model1 <- lm(slatkin_D ~ distance, data=pair_fst_dist)
summary(IBD.model1)
anova(IBD.model1)


IDB2 <- ggplot(data=pair_fst_dist, aes(x=distance, y=slatkin_D))+
  geom_point(aes(fill=ew_gradient), size=3, shape=21,
             alpha=.4)+
  geom_smooth(method="lm", se=F, fullrange=T, aes(color=ew_gradient),
              linetype="dashed",
              linewidth=1.5)+
  xlab("Distance (km)") +
  ylab("Slatkin's D") +
  scale_fill_manual(values=c("blue", "purple", "red"))+
  scale_color_manual(values=c("blue", "purple", "red"))+
  labs(color="KEY", fill="KEY")+
  theme_classic()+
  #theme(legend.position = "none")+
  theme_font1()

pdf("IDB-color.coded-final2.pdf", height=5, width=7)
IDB2
dev.off()

## simple model
IBD.model2 <- lm(slatkin_D ~ distance*ew_gradient, data=filter(pair_fst_dist, ew_gradient != "NA"))
summary(IBD.model2)
anova(IBD.model2)

IBD.trends <- emtrends(IBD.model2, specs = "ew_gradient", var = "distance")
IBD.trends

contrast(IBD.trends, method = "pairwise")
```


## Check which pairs are missing

```{r}
all.sites <- c(sites$site)
# Generate all possible pairs
all_pairs <- combn(all.sites, 2)

# Convert pairs to strings for comparison
all_pairs_strings <- apply(all_pairs, 2, function(x) paste(sort(x), collapse = "-"))

# Convert pairs in your dataset to strings
your_pairs_strings <- apply(pair_fst_dist[, c("site1", "site2")], 1, function(x) paste(sort(x), collapse = "-"))

# Find missing pairs
missing_pairs <- setdiff(all_pairs_strings, your_pairs_strings)

# Print missing pairs
print(missing_pairs)
```

## Mantel test

```{r}
library(geosphere)

#sites<-read.csv("Data/sites.csv")

# Haversine distance
mantel.pair_dist <- distm(sites[, c("x", "y")], fun = distHaversine)
rownames(mantel.pair_dist) <- sites$name
colnames(mantel.pair_dist) <- sites$name

# geo matrix
geo_dist <- as.dist(mantel.pair_dist)

## Fst matrix
mantel.pair_fst <- matrix(0, nrow = length(sites$site), ncol = length(sites$site))
rownames(mantel.pair_fst) <- sites$site
colnames(mantel.pair_fst) <- sites$site

# fill in the matrix with Fst values
for (i in 1:nrow(pair_fst_dist)) {
  site1 <- pair_fst_dist$site1[i]
  site2 <- pair_fst_dist$site2[i]
  fst <- pair_fst_dist$Weighted_Fst[i]
  
  mantel.pair_fst[site1, site2] <- fst
  mantel.pair_fst[site2, site1] <- fst # Assuming the matrix is symmetric
}

# Convert the matrix to a distance object
fst_dist <- as.dist(mantel.pair_fst)


mantel1 <- mantel(fst_dist, geo_dist)
print(mantel1)
```

## Mantel test: East vs. west 
```{r}
#### subset east vs. west - change code for east####
sites.sub <- sites %>% filter(divide=="west")
  
mantel.pair_dist <- distm(sites.sub[, c("x", "y")], fun = distHaversine)
rownames(mantel.pair_dist) <- sites.sub$name
colnames(mantel.pair_dist) <- sites.sub$name

# geo matrix
geo_dist.sub <- as.dist(mantel.pair_dist)

# ## Fst matrix
# mantel.pair_fst <- matrix(0, nrow = length(sites.sub$site), ncol = length(sites.sub$site))
# rownames(mantel.pair_fst) <- sites.sub$site
# colnames(mantel.pair_fst) <- sites.sub$site
# 
# # fill in the matrix with Fst values
# fst_dist <- as.dist(mantel.pair_fst)

# List of names to be removed
remove_sites <- c("LL", "SP", "NF", "SC", "LF", "HT", "FV", "WY")

# Subset the matrix by keeping only the sites that are NOT in the remove_sites list
# Remove !s for eastern sites only

fst_dist_sub1 <- as.matrix(fst_dist)
fst_dist_sub <- as.matrix(fst_dist_sub1[!rownames(fst_dist_sub1) %in% remove_sites, 
                            !colnames(fst_dist_sub1) %in% remove_sites])


mantel.sub <- mantel(fst_dist_sub, geo_dist.sub, permutations=999)
print(mantel.sub)
```

